steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/microservices-426101/image-registry/orders-ms-prod",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
    env:
    - "ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/microservices-426101/image-registry/orders-ms-prod",
      ]
options:
  logging: CLOUD_LOGGING_ONLY